import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
  },
  heroWrapper: {
    position: 'relative',
    minHeight: 320,
  },
  heroImage: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 320,
  },
  heroImageStyle: {},
  heroGradient: {
    flex: 1,
  },
  heroContent: {
    paddingTop: 40,
    paddingBottom: 24,
    paddingHorizontal: 24,
    alignItems: 'center',
  },
  logoBadge: {
    width: 64,
    height: 64,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 20,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.35,
    shadowRadius: 16,
    elevation: 6,
  },
  title: {
    fontSize: 30,
    fontFamily: 'BeVietnamPro-Bold',
    letterSpacing: -0.5,
    textAlign: 'center',
  },
  subtitle: {
    marginTop: 8,
    fontSize: 14,
    fontFamily: 'NotoSans-Medium',
    textAlign: 'center',
    maxWidth: 280,
  },
  formSection: {
    paddingHorizontal: 24,
    paddingTop: 8,
  },
  formCard: {
    borderRadius: 24,
    borderWidth: 1,
    paddingHorizontal: 16,
    paddingTop: 18,
    paddingBottom: 20,
  },
  avatarSection: {
    alignItems: 'center',
    marginBottom: 24,
  },
  avatarWrapper: {
    width: 112,
    height: 112,
  },
  avatarImage: {
    width: 112,
    height: 112,
    borderRadius: 56,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderStyle: 'dashed',
    overflow: 'hidden',
  },
  avatarBadge: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    width: 28,
    height: 28,
    borderRadius: 14,
    borderWidth: 3,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarLabel: {
    marginTop: 12,
    fontSize: 13,
    fontFamily: 'NotoSans-Medium',
  },
  avatarError: {
    marginTop: 8,
    fontSize: 12,
    textAlign: 'center',
    fontFamily: 'NotoSans-Medium',
  },
  fieldGroup: {
    marginBottom: 18,
  },
  label: {
    fontSize: 13,
    fontFamily: 'NotoSans-Medium',
    marginBottom: 8,
  },
  input: {
    height: 56,
    borderRadius: 16,
    paddingHorizontal: 16,
    borderWidth: 1,
    fontSize: 16,
    fontFamily: 'NotoSans-Regular',
  },
  handleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    height: 56,
    borderRadius: 16,
    borderWidth: 1,
    paddingHorizontal: 12,
    gap: 6,
  },
  handlePrefix: {
    fontSize: 16,
    fontFamily: 'NotoSans-Medium',
  },
  handleInput: {
    flex: 1,
    fontSize: 16,
    fontFamily: 'NotoSans-Regular',
  },
  helperText: {
    marginTop: 6,
    fontSize: 12,
    fontFamily: 'NotoSans-Regular',
  },
  textareaWrapper: {
    position: 'relative',
  },
  counterText: {
    position: 'absolute',
    right: 12,
    bottom: 10,
    fontSize: 12,
    fontFamily: 'NotoSans-Medium',
  },
  textarea: {
    minHeight: 110,
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 30,
    borderWidth: 1,
    fontSize: 15,
    fontFamily: 'NotoSans-Regular',
    textAlignVertical: 'top',
  },
  visibilityGrid: {
    flexDirection: 'row',
    gap: 12,
  },
  visibilityCard: {
    flex: 1,
  },
  visibilityCardInner: {
    borderRadius: 16,
    padding: 12,
    alignItems: 'center',
    borderWidth: 2,
  },
  visibilityTitle: {
    fontSize: 13,
    fontFamily: 'BeVietnamPro-Bold',
    marginTop: 6,
  },
  visibilityDesc: {
    fontSize: 12,
    fontFamily: 'NotoSans-Regular',
    textAlign: 'center',
    marginTop: 4,
  },
  visibilityCheck: {
    position: 'absolute',
    top: 8,
    right: 8,
  },
  primaryButton: {
    height: 56,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 6,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.25,
    shadowRadius: 20,
    elevation: 4,
  },
  primaryButtonText: {
    fontSize: 16,
    fontFamily: 'BeVietnamPro-Bold',
  },
  formErrorText: {
    marginTop: 10,
    fontSize: 12,
    fontFamily: 'NotoSans-Medium',
    textAlign: 'center',
  },
});
