import * as Localization from 'expo-localization';

const STRINGS = {
  'en-US': {
    auth: {
      appName: 'MapFriends',
      loginTitle: 'MapFriends',
      loginSubtitle: 'Log in to see recommendations from your circle.',
      signupTitle: 'Create your profile',
      signupSubtitle: 'Start sharing local favorites.',
      nameLabel: 'Name',
      namePlaceholder: 'Your name',
      emailLabel: 'Email',
      emailPlaceholder: 'name@example.com',
      passwordLabel: 'Password',
      passwordPlaceholder: 'Enter your password',
      confirmPasswordLabel: 'Confirm password',
      confirmPasswordPlaceholder: 'Re-enter your password',
      confirmPasswordMismatch: 'Passwords do not match.',
      togglePasswordVisibility: 'Toggle password visibility',
      forgotPassword: 'Forgot password?',
      loginButton: 'Log in',
      signupButton: 'Create account',
      divider: 'Or continue with',
      socialGoogle: 'Google',
      socialApple: 'Apple',
      noAccount: "Don't have an account?",
      createAccount: 'Create account',
      haveAccount: 'Already have an account?',
      backToLogin: 'Back to log in',
      resetPasswordSent: 'Password reset email sent.',
      firebaseNotConfigured: 'Firebase configuration is missing. Check your environment variables.',
      authErrorInvalidCredentials: 'Invalid email or password.',
      authErrorEmailInUse: 'This email is already in use.',
      authErrorInvalidEmail: 'Enter a valid email address.',
      authErrorWeakPassword: 'Password must have at least 6 characters.',
      authErrorUserDisabled: 'This account has been disabled.',
      authErrorTooManyRequests: 'Too many attempts. Try again in a few minutes.',
      authErrorNetwork: 'Network error. Check your internet connection.',
      authErrorProviderCanceled: 'Authentication was canceled.',
      authErrorProviderUnavailable: 'This sign-in provider is not configured yet.',
      authErrorGeneric: 'Could not authenticate right now. Please try again.',
      loadingA11y: 'Loading',
    },
    terms: {
      title: 'Legal Agreements',
      subtitle: 'Please review our terms to continue using the social map.',
      section1Title: '1. Terms of Service',
      section1Paragraph1:
        'By using our social map recommendation platform, you agree to share your location data and visibility preferences with the followers you have approved. Our subscription model for premium reviews provides access to curated content from verified local experts.',
      section1Paragraph2:
        'You are responsible for maintaining the confidentiality of your account and for all activities that occur under your account. You agree to notify us immediately of any unauthorized use.',
      section2Title: '2. Privacy Policy Summary',
      section2Paragraph1:
        'Your privacy is our priority. We only show your pins and reviews to people you explicitly follow back. Your location history is encrypted and never sold to third-party advertisers.',
      section2Paragraph2:
        'Premium reviews are subject to specific licensing agreements. Copying or redistributing premium content without a valid subscription is strictly prohibited.',
      section3Title: '3. Community Standards',
      section3Paragraph1:
        'Users must refrain from posting offensive content, spam, or misleading reviews. Violation of community standards may result in temporary or permanent suspension of your account and subscription.',
      acceptTermsPrefix: 'I agree to the ',
      acceptTermsLink: 'Terms of Service',
      acceptPrivacyPrefix: 'I agree to the ',
      acceptPrivacyLink: 'Privacy Policy',
      acceptButton: 'Accept and Continue',
      declineButton: 'Decline and Exit',
    },
    profileSetup: {
      title: 'Profile Setup',
      subtitle: 'Create your profile so friends can recognize your map activity.',
      skip: 'Skip',
      avatarLabel: 'Upload Avatar',
      displayNameLabel: 'Display Name',
      displayNamePlaceholder: 'e.g. Alex Explorer',
      handleLabel: 'Handle',
      handlePlaceholder: 'username',
      handleHelper: 'Your unique handle on the map.',
      handleError: 'Use 3–20 characters: lowercase letters, numbers, or underscore.',
      handleSanitizedHelper: 'Unsupported characters were removed.',
      bioLabel: 'Bio',
      bioPlaceholder: 'Share your favorite spots or travel style...',
      bioMax: 150,
      visibilityLabel: 'Profile Visibility',
      visibilityOpenTitle: 'Open',
      visibilityOpenDesc: 'Anyone can see your map',
      visibilityLockedTitle: 'Locked',
      visibilityLockedDesc: 'Only followers see pins',
      continueButton: 'Continue',
      skipA11yLabel: 'Skip profile setup',
      skipA11yHint: 'Continue without completing this profile now',
      avatarAddA11yLabel: 'Add profile avatar',
      avatarChangeA11yLabel: 'Change profile avatar',
      avatarA11yHint: 'Opens your photo library',
      avatarPermissionDenied: 'Allow photo access in Settings to choose an avatar.',
      avatarPickerError: 'Could not open the photo library. Please try again.',
      visibilityOpenA11yLabel: 'Set profile visibility to open',
      visibilityLockedA11yLabel: 'Set profile visibility to locked',
      continueA11yLabel: 'Continue profile setup',
      continueA11yHint: 'Saves profile and continues to onboarding',
    },
    home: {
      tabFeed: 'Feed',
      tabMap: 'Map',
      filterPeopleAll: 'People: All',
      filterContentPremium: 'Content: Premium',
      youLabel: 'You',
      sampleQuote: 'Elena says: "Best broth in town!"',
      feedSubtitle: 'Latest recommendations from your circle.',
      feedTitle: 'SocialMap',
      feedMore: 'more',
      feedPremiumLabel: 'Premium',
      feedPremiumTitle: 'Unlock Full Review',
      feedPremiumDesc: "Join Premium to see Mike's rating and read the full details.",
      feedPremiumCta: 'Subscribe',
      navHome: 'Home',
      navExplore: 'Explore',
      navActivity: 'Activity',
      navProfile: 'Profile',
      mapTokenMissing: 'Add EXPO_PUBLIC_MAPBOX_TOKEN to enable the map.',
      exploreTitle: 'Explore',
      exploreSubtitle: 'Search and discover new places.',
    },
    search: {
      placeholder: 'Search people or places...',
      cancel: 'Cancel',
      tabPeople: 'People',
      tabPlaces: 'Places',
      recentTitle: 'Recent Searches',
      recentPlacesTitle: 'Recent Places',
      trendingTitle: 'Trending Creators',
      trendingPlacesTitle: 'Trending Places',
      clearAll: 'Clear All',
      infoMessage:
        "To maintain a curated experience, you'll only see reviews and pins from people you follow. Connect with friends or follow trending creators to populate your map.",
      follow: 'Follow',
      following: 'Following',
      proBadge: 'PRO',
    },
    profile: {
      title: 'Settings',
      handlePrefix: '@',
      subtitle: 'Premium Creator & Guide',
      editProfile: 'Edit Profile',
      sectionPrivacy: 'Account Privacy',
      visibilityTitle: 'Profile Visibility',
      visibilitySubtitle: 'Locked accounts require approval',
      sectionCreator: 'Creator Hub',
      creatorSettings: 'Creator Settings',
      subscriberManagement: 'Subscribers Management',
      subscriberCount: '124',
      sectionPreferences: 'Preferences',
      manageSubscriptions: 'Manage My Subscriptions',
      blockedUsers: 'Blocked Users',
      logout: 'Logout',
      versionLabel: 'Version 2.4.0 (Build 402)',
    },
    reviewComposer: {
      title: 'Write Review',
      cancel: 'Cancel',
      post: 'Post',
      ratingLabel: 'Your Rating',
      placeholder: 'Share your experience with your followers... What made this place special?',
      photosLabel: 'Photos',
      photosCount: '{count}/10',
      visibilityLabel: 'Visibility',
      visibilityInfo: 'What is this?',
      visibilityFollowers: 'Followers',
      visibilitySubscribers: 'Subscribers Only',
      visibilityHelper:
        'By selecting Subscribers Only, you earn 2x points on this review. Only your paid subscribers can view full details.',
      defaultTitle: 'Great spot',
      defaultNotes: 'Sharing a quick recommendation.',
      locationFallback: 'Select a place',
    },
    notifications: {
      title: 'Notifications',
      clear: 'Clear',
      sectionNew: 'New Requests',
      sectionEarlier: 'Earlier Today',
      sectionWeek: 'This Week',
      accept: 'Accept',
      decline: 'Decline',
      followBack: 'Follow back',
      premiumTitle: 'Unlock Premium Review',
      premiumSubtitle: 'Included in your subscription',
      premiumCta: 'View',
    },
  },
  'pt-BR': {
    auth: {
      appName: 'MapFriends',
      loginTitle: 'MapFriends',
      loginSubtitle: 'Faça login para ver recomendações do seu círculo.',
      signupTitle: 'Crie seu perfil',
      signupSubtitle: 'Comece a compartilhar favoritos locais.',
      nameLabel: 'Nome',
      namePlaceholder: 'Seu nome',
      emailLabel: 'E-mail',
      emailPlaceholder: 'nome@exemplo.com',
      passwordLabel: 'Senha',
      passwordPlaceholder: 'Digite sua senha',
      confirmPasswordLabel: 'Confirmar senha',
      confirmPasswordPlaceholder: 'Digite a senha novamente',
      confirmPasswordMismatch: 'As senhas nao correspondem.',
      togglePasswordVisibility: 'Mostrar ou ocultar senha',
      forgotPassword: 'Esqueceu a senha?',
      loginButton: 'Entrar',
      signupButton: 'Criar conta',
      divider: 'Ou continue com',
      socialGoogle: 'Google',
      socialApple: 'Apple',
      noAccount: 'Não tem uma conta?',
      createAccount: 'Criar conta',
      haveAccount: 'Já tem uma conta?',
      backToLogin: 'Voltar para entrar',
      resetPasswordSent: 'E-mail de redefinição de senha enviado.',
      firebaseNotConfigured: 'A configuração do Firebase está ausente. Verifique as variáveis de ambiente.',
      authErrorInvalidCredentials: 'E-mail ou senha inválidos.',
      authErrorEmailInUse: 'Este e-mail já está em uso.',
      authErrorInvalidEmail: 'Digite um e-mail válido.',
      authErrorWeakPassword: 'A senha deve ter pelo menos 6 caracteres.',
      authErrorUserDisabled: 'Esta conta foi desativada.',
      authErrorTooManyRequests: 'Muitas tentativas. Tente novamente em alguns minutos.',
      authErrorNetwork: 'Erro de rede. Verifique sua conexão com a internet.',
      authErrorProviderCanceled: 'A autenticação foi cancelada.',
      authErrorProviderUnavailable: 'Este provedor de login ainda não está configurado.',
      authErrorGeneric: 'Não foi possível autenticar agora. Tente novamente.',
      loadingA11y: 'Carregando',
    },
    terms: {
      title: 'Acordos legais',
      subtitle: 'Revise nossos termos para continuar usando o mapa social.',
      section1Title: '1. Termos de Serviço',
      section1Paragraph1:
        'Ao usar nossa plataforma de recomendações com mapa social, você concorda em compartilhar seus dados de localização e preferências de visibilidade com os seguidores que você aprovou. Nosso modelo de assinatura para avaliações premium oferece acesso a conteúdo curado de especialistas locais verificados.',
      section1Paragraph2:
        'Você é responsável por manter a confidencialidade da sua conta e por todas as atividades realizadas nela. Você concorda em nos notificar imediatamente sobre qualquer uso não autorizado.',
      section2Title: '2. Resumo da Política de Privacidade',
      section2Paragraph1:
        'Sua privacidade é nossa prioridade. Só mostramos seus pins e avaliações para pessoas que você segue de volta. Seu histórico de localização é criptografado e nunca é vendido a anunciantes terceiros.',
      section2Paragraph2:
        'Avaliações premium estão sujeitas a acordos específicos de licenciamento. Copiar ou redistribuir conteúdo premium sem uma assinatura válida é estritamente proibido.',
      section3Title: '3. Padrões da Comunidade',
      section3Paragraph1:
        'Os usuários devem se abster de publicar conteúdo ofensivo, spam ou avaliações enganosas. A violação dos padrões da comunidade pode resultar em suspensão temporária ou permanente da sua conta e assinatura.',
      acceptTermsPrefix: 'Concordo com os ',
      acceptTermsLink: 'Termos de Serviço',
      acceptPrivacyPrefix: 'Concordo com a ',
      acceptPrivacyLink: 'Política de Privacidade',
      acceptButton: 'Aceitar e continuar',
      declineButton: 'Recusar e sair',
    },
    profileSetup: {
      title: 'Configuração do perfil',
      subtitle: 'Monte seu perfil para que amigos reconheçam sua atividade no mapa.',
      skip: 'Pular',
      avatarLabel: 'Enviar avatar',
      displayNameLabel: 'Nome de exibição',
      displayNamePlaceholder: 'ex.: Alex Explorer',
      handleLabel: 'Usuário',
      handlePlaceholder: 'usuario',
      handleHelper: 'Seu identificador único no mapa.',
      handleError: 'Use 3–20 caracteres: letras minúsculas, números ou _.',
      handleSanitizedHelper: 'Caracteres não suportados foram removidos.',
      bioLabel: 'Bio',
      bioPlaceholder: 'Compartilhe seus lugares favoritos ou estilo de viagem...',
      bioMax: 150,
      visibilityLabel: 'Visibilidade do perfil',
      visibilityOpenTitle: 'Aberto',
      visibilityOpenDesc: 'Qualquer pessoa pode ver seu mapa',
      visibilityLockedTitle: 'Bloqueado',
      visibilityLockedDesc: 'Apenas seguidores veem pins',
      continueButton: 'Continuar',
      skipA11yLabel: 'Pular configuração do perfil',
      skipA11yHint: 'Continue sem concluir este perfil agora',
      avatarAddA11yLabel: 'Adicionar avatar do perfil',
      avatarChangeA11yLabel: 'Alterar avatar do perfil',
      avatarA11yHint: 'Abre sua biblioteca de fotos',
      avatarPermissionDenied: 'Permita acesso às fotos nos Ajustes para escolher um avatar.',
      avatarPickerError: 'Não foi possível abrir a biblioteca de fotos. Tente novamente.',
      visibilityOpenA11yLabel: 'Definir visibilidade do perfil como aberto',
      visibilityLockedA11yLabel: 'Definir visibilidade do perfil como bloqueado',
      continueA11yLabel: 'Continuar configuração de perfil',
      continueA11yHint: 'Salva o perfil e continua para a introdução',
    },
    home: {
      tabFeed: 'Feed',
      tabMap: 'Mapa',
      filterPeopleAll: 'Pessoas: Todas',
      filterContentPremium: 'Conteúdo: Premium',
      youLabel: 'Você',
      sampleQuote: 'Elena diz: "Melhor caldo da cidade!"',
      feedSubtitle: 'Recomendações recentes do seu círculo.',
      feedTitle: 'SocialMap',
      feedMore: 'mais',
      feedPremiumLabel: 'Premium',
      feedPremiumTitle: 'Desbloqueie a avaliação completa',
      feedPremiumDesc: 'Assine o Premium para ver a nota do Mike e ler todos os detalhes.',
      feedPremiumCta: 'Assinar',
      navHome: 'Início',
      navExplore: 'Explorar',
      navActivity: 'Atividade',
      navProfile: 'Perfil',
      mapTokenMissing: 'Adicione EXPO_PUBLIC_MAPBOX_TOKEN para ativar o mapa.',
      exploreTitle: 'Explorar',
      exploreSubtitle: 'Pesquise e descubra novos lugares.',
    },
    search: {
      placeholder: 'Buscar pessoas ou lugares...',
      cancel: 'Cancelar',
      tabPeople: 'Pessoas',
      tabPlaces: 'Lugares',
      recentTitle: 'Pesquisas recentes',
      recentPlacesTitle: 'Lugares recentes',
      trendingTitle: 'Criadores em alta',
      trendingPlacesTitle: 'Lugares em alta',
      clearAll: 'Limpar tudo',
      infoMessage:
        'Para manter uma experiência curada, você só verá avaliações e pins de pessoas que segue. Conecte-se com amigos ou siga criadores em alta para preencher seu mapa.',
      follow: 'Seguir',
      following: 'Seguindo',
      proBadge: 'PRO',
    },
    profile: {
      title: 'Configurações',
      handlePrefix: '@',
      subtitle: 'Criador premium e guia',
      editProfile: 'Editar perfil',
      sectionPrivacy: 'Privacidade da conta',
      visibilityTitle: 'Visibilidade do perfil',
      visibilitySubtitle: 'Contas bloqueadas exigem aprovação',
      sectionCreator: 'Central do criador',
      creatorSettings: 'Configurações do criador',
      subscriberManagement: 'Gestão de assinantes',
      subscriberCount: '124',
      sectionPreferences: 'Preferências',
      manageSubscriptions: 'Gerenciar minhas assinaturas',
      blockedUsers: 'Usuários bloqueados',
      logout: 'Sair',
      versionLabel: 'Versão 2.4.0 (Build 402)',
    },
    reviewComposer: {
      title: 'Escrever avaliação',
      cancel: 'Cancelar',
      post: 'Publicar',
      ratingLabel: 'Sua nota',
      placeholder: 'Compartilhe sua experiência... O que tornou esse lugar especial?',
      photosLabel: 'Fotos',
      photosCount: '{count}/10',
      visibilityLabel: 'Visibilidade',
      visibilityInfo: 'O que é isso?',
      visibilityFollowers: 'Seguidores',
      visibilitySubscribers: 'Apenas assinantes',
      visibilityHelper:
        'Ao selecionar Apenas assinantes, você ganha 2x pontos nesta avaliação. Só seus assinantes pagos podem ver todos os detalhes.',
      defaultTitle: 'Ótimo lugar',
      defaultNotes: 'Compartilhando uma recomendação rápida.',
      locationFallback: 'Selecione um lugar',
    },
    notifications: {
      title: 'Notificações',
      clear: 'Limpar',
      sectionNew: 'Novos pedidos',
      sectionEarlier: 'Hoje mais cedo',
      sectionWeek: 'Esta semana',
      accept: 'Aceitar',
      decline: 'Recusar',
      followBack: 'Seguir de volta',
      premiumTitle: 'Desbloquear avaliação premium',
      premiumSubtitle: 'Incluído na sua assinatura',
      premiumCta: 'Ver',
    },
  },
} as const;

type SupportedLocale = keyof typeof STRINGS;

function resolveLocale(): SupportedLocale {
  const locale = Localization.getLocales?.()?.[0];
  const tag = (locale?.languageTag || 'en-US').toLowerCase();

  if (tag.startsWith('pt')) {
    return 'pt-BR';
  }

  return 'en-US';
}

export function getStrings() {
  return STRINGS[resolveLocale()];
}
