import * as Localization from 'expo-localization';

const STRINGS = {
  'en-US': {
    auth: {
      appName: 'MapFriends',
      loginTitle: 'MapFriends',
      loginSubtitle: 'Log in to see recommendations from your circle.',
      signupTitle: 'Create your profile',
      signupSubtitle: 'Start sharing local favorites.',
      nameLabel: 'Name',
      namePlaceholder: 'Your name',
      emailLabel: 'Email',
      emailPlaceholder: 'name@example.com',
      passwordLabel: 'Password',
      passwordPlaceholder: 'Enter your password',
      confirmPasswordLabel: 'Confirm password',
      confirmPasswordPlaceholder: 'Re-enter your password',
      confirmPasswordMismatch: 'Passwords do not match.',
      togglePasswordVisibility: 'Toggle password visibility',
      forgotPassword: 'Forgot password?',
      loginButton: 'Log in',
      signupButton: 'Create account',
      divider: 'Or continue with',
      socialGoogle: 'Google',
      socialApple: 'Apple',
      noAccount: "Don't have an account?",
      createAccount: 'Create account',
      haveAccount: 'Already have an account?',
      backToLogin: 'Back to log in',
      resetPasswordSent: 'Password reset email sent.',
      firebaseNotConfigured: 'Firebase configuration is missing. Check your environment variables.',
      authErrorInvalidCredentials: 'Invalid email or password.',
      authErrorEmailInUse: 'This email is already in use.',
      authErrorInvalidEmail: 'Enter a valid email address.',
      authErrorWeakPassword: 'Password must have at least 6 characters.',
      authErrorUserDisabled: 'This account has been disabled.',
      authErrorTooManyRequests: 'Too many attempts. Try again in a few minutes.',
      authErrorNetwork: 'Network error. Check your internet connection.',
      authErrorRecentLogin: 'Please log in again before deleting your account.',
      authErrorDeleteEmailMismatch: 'The confirmation email does not match your account email.',
      authErrorProviderCanceled: 'Authentication was canceled.',
      authErrorProviderUnavailable: 'This sign-in provider is not configured yet.',
      authErrorGeneric: 'Could not authenticate right now. Please try again.',
      loadingA11y: 'Loading',
    },
    terms: {
      title: 'Legal Agreements',
      subtitle: 'Please review our terms to continue using the social map.',
      section1Title: '1. Terms of Service',
      section1Paragraph1:
        'By using our social map recommendation platform, you agree to share your location data and visibility preferences with the followers you have approved. Our subscription model for premium reviews provides access to curated content from verified local experts.',
      section1Paragraph2:
        'You are responsible for maintaining the confidentiality of your account and for all activities that occur under your account. You agree to notify us immediately of any unauthorized use.',
      section2Title: '2. Privacy Policy Summary',
      section2Paragraph1:
        'Your privacy is our priority. We only show your pins and reviews to people you explicitly follow back. Your location history is encrypted and never sold to third-party advertisers.',
      section2Paragraph2:
        'Premium reviews are subject to specific licensing agreements. Copying or redistributing premium content without a valid subscription is strictly prohibited.',
      section3Title: '3. Community Standards',
      section3Paragraph1:
        'Users must refrain from posting offensive content, spam, or misleading reviews. Violation of community standards may result in temporary or permanent suspension of your account and subscription.',
      acceptTermsPrefix: 'I agree to the ',
      acceptTermsLink: 'Terms of Service',
      acceptPrivacyPrefix: 'I agree to the ',
      acceptPrivacyLink: 'Privacy Policy',
      acceptButton: 'Accept and Continue',
      declineButton: 'Decline and Exit',
    },
    profileSetup: {
      title: 'Profile Setup',
      subtitle: 'Create your profile so friends can recognize your map activity.',
      avatarLabel: 'Upload Avatar',
      displayNameLabel: 'Display Name',
      displayNamePlaceholder: 'e.g. Alex Explorer',
      handleLabel: 'Handle',
      handlePlaceholder: 'username',
      handleHelper: 'Your unique handle on the map.',
      handleError: 'Use 3–20 characters: lowercase letters, numbers, or underscore.',
      handleChecking: 'Checking handle availability...',
      handleAvailable: 'Handle available.',
      handleTaken: 'This handle is already taken.',
      handleReserved: 'This handle is reserved and cannot be used.',
      handleImmutable: 'Your handle is already set and cannot be changed.',
      handleSanitizedHelper: 'Unsupported characters were removed.',
      bioLabel: 'Bio',
      bioPlaceholder: 'Share your favorite spots or travel style...',
      bioMax: 150,
      visibilityLabel: 'Profile Visibility',
      visibilityOpenTitle: 'Open',
      visibilityOpenDesc: 'Anyone can see your map',
      visibilityLockedTitle: 'Locked',
      visibilityLockedDesc: 'Only followers see pins',
      continueButton: 'Continue',
      avatarAddA11yLabel: 'Add profile avatar',
      avatarChangeA11yLabel: 'Change profile avatar',
      avatarA11yHint: 'Opens your photo library',
      avatarPermissionDenied: 'Allow photo access in Settings to choose an avatar.',
      avatarPickerError: 'Could not open the photo library. Please try again.',
      visibilityOpenA11yLabel: 'Set profile visibility to open',
      visibilityLockedA11yLabel: 'Set profile visibility to locked',
      continueA11yLabel: 'Continue profile setup',
      continueA11yHint: 'Saves profile and continues to onboarding',
    },
    home: {
      tabFeed: 'Feed',
      tabMap: 'Map',
      filterPeopleAll: 'People: All',
      filterContentPremium: 'Content: Premium',
      youLabel: 'You',
      sampleQuote: 'Elena says: "Best broth in town!"',
      feedSubtitle: 'Latest recommendations from your circle.',
      feedTitle: 'SocialMap',
      feedMore: 'more',
      feedPremiumLabel: 'Premium',
      feedPremiumTitle: 'Unlock Full Review',
      feedPremiumDesc: "Join Premium to see Mike's rating and read the full details.",
      feedPremiumCta: 'Subscribe',
      feedEmptyTitle: 'A quiet page, waiting for your first place.',
      feedEmptySubtitle:
        'Nothing has been shared yet. Your next recommendation can become someone else’s favorite memory.',
      feedEmptyCta: 'Share your first review',
      feedEmptyFootnote: 'Leave a small mark. Let the city answer.',
      feedActionAuthTitle: 'Authentication required',
      feedActionAuthMessage: 'Please sign in again to use this action.',
      feedShareTitle: 'Share review',
      feedShareSubtitlePrefix: 'Share',
      feedShareSystem: 'Share via system',
      feedShareCopyLink: 'Copy link',
      feedShareCopySuccessTitle: 'Link copied',
      feedShareCopySuccessMessage: 'Review link copied to clipboard.',
      feedShareCopyErrorTitle: 'Could not copy link',
      feedShareCopyErrorMessage: 'Please try again.',
      feedShareCancel: 'Cancel',
      feedLikeErrorTitle: 'Could not update like',
      feedLikeErrorMessage: 'Please try again in a moment.',
      feedFavoriteErrorTitle: 'Could not update favorite',
      feedFavoriteErrorMessage: 'Please try again in a moment.',
      feedShareErrorTitle: 'Could not open share',
      feedShareErrorMessage: 'Please try again.',
      navHome: 'Home',
      navExplore: 'Explore',
      navActivity: 'Activity',
      navProfile: 'Profile',
      mapTokenMissing: 'Add EXPO_PUBLIC_MAPBOX_TOKEN to enable the map.',
      locationPromptTitle: 'Enable your location',
      locationPromptMessage:
        'We use your location to show nearby recommendations and personalized map content.',
      locationPromptAllow: 'Allow location',
      locationPromptNotNow: 'Not now',
      exploreTitle: 'Explore',
      exploreSubtitle: 'Search and discover new places.',
    },
    search: {
      placeholder: 'Search by name or @handle...',
      cancel: 'Cancel',
      recentTitle: 'Recent Searches',
      recentEmptyTitle: 'No recent searches yet',
      recentEmptySubtitle: 'Search for someone and tap their profile to save it here.',
      trendingTitle: 'Trending Creators',
      trendingEmptyTitle: 'No creators trending right now',
      trendingEmptySubtitle: 'As new reviews are published, top creators for this week show up here.',
      resultsTitle: 'People',
      resultsEmptyTitle: 'No people found',
      resultsEmptySubtitle: 'Try another name or handle.',
      minQueryTitle: 'Keep typing',
      minQuerySubtitle: 'Type at least 2 characters to search.',
      clearAll: 'Clear All',
      infoMessage:
        "To maintain a curated experience, you'll only see reviews and pins from people you follow. Connect with friends or follow trending creators to populate your map.",
      follow: 'Follow',
      following: 'Following',
      request: 'Request',
      requested: 'Requested',
      locked: 'Locked',
      postsThisWeek: '{count} posts this week',
      followErrorTitle: 'Could not complete action',
      followErrorMessage: 'Please try again.',
      proBadge: 'PRO',
    },
    profile: {
      title: 'Settings',
      handlePrefix: '@',
      subtitle: 'Premium Creator & Guide',
      tabSettings: 'Settings',
      tabFavorites: 'Favorites',
      editProfile: 'Edit Profile',
      editScreenTitle: 'Edit Profile',
      editNameLabel: 'Display Name',
      editNamePlaceholder: 'e.g. Alex Explorer',
      editHandleLabel: 'Handle',
      editBioLabel: 'Bio',
      editBioPlaceholder: 'Share your favorite spots or travel style...',
      editAvatarLabel: 'Change avatar',
      editAvatarPermissionDenied: 'Allow photo access in Settings to choose an avatar.',
      editAvatarPickerError: 'Could not open the photo library. Please try again.',
      editSave: 'Save Changes',
      editSaving: 'Saving...',
      deleteAccount: 'Delete account',
      deleteSheetTitle: 'Delete account permanently?',
      deleteSheetMessage:
        'This action cannot be undone. All your profile data and account access will be removed.',
      deleteSheetEmailLabel: 'Type your email to confirm',
      deleteSheetEmailPlaceholder: 'name@example.com',
      deleteSheetCancel: 'Cancel',
      deleteSheetConfirm: 'Delete my account',
      sectionPrivacy: 'Account Privacy',
      visibilityTitle: 'Profile Visibility',
      visibilitySubtitle: 'Locked accounts require approval',
      sectionCreator: 'Creator Hub',
      creatorSettings: 'Creator Settings',
      subscriberManagement: 'Subscribers Management',
      subscriberCount: '124',
      sectionPreferences: 'Preferences',
      manageSubscriptions: 'Manage My Subscriptions',
      manageSubscriptionsComingSoon: 'Coming soon',
      manageSubscriptionsComingSoonSubtitle: 'Subscription details and billing controls will appear here when this feature goes live.',
      blockedUsers: 'Blocked Users',
      blockedUsersTitle: 'Manage blocked users',
      blockedUsersSubtitle: 'People you block cannot interact with your profile or content until you unblock them.',
      blockedUsersEmptyTitle: 'No blocked users',
      blockedUsersEmptySubtitle: 'When you block someone, they will appear here so you can manage access.',
      blockedUsersErrorTitle: 'Could not load blocked users',
      blockedUsersErrorSubtitle: 'Pull down to try again.',
      blockedUsersUnblockLabel: 'Unblock',
      blockedUsersBlockedOnPrefix: 'Blocked on',
      blockedUsersBlockedRecently: 'recently',
      blockedUsersUnblockConfirmTitle: 'Unblock this user?',
      blockedUsersUnblockConfirmMessage: '{handle} will be able to see and interact with your content again.',
      blockedUsersUnblockConfirmCancel: 'Cancel',
      blockedUsersUnblockConfirmAction: 'Unblock',
      blockedUsersUnblockErrorTitle: 'Could not unblock user',
      blockedUsersUnblockErrorMessage: 'Please try again.',
      favoritesTitle: 'Saved favorites',
      favoritesSubtitle: 'Places and reviews you chose to keep.',
      favoritesEmptyTitle: 'No favorites yet',
      favoritesEmptySubtitle: 'Open a review and tap Save to favorites to build your list.',
      favoritesRemoveLabel: 'Remove from favorites',
      logout: 'Logout',
      logoutConfirmTitle: 'Log out of your account?',
      logoutConfirmMessage: 'You will need to log in again to continue.',
      logoutConfirmCancel: 'Cancel',
      logoutConfirmConfirm: 'Log out',
      logoutErrorTitle: 'Could not log out',
      logoutErrorMessage: 'Please try again.',
      loggingOut: 'Logging out...',
      versionLabel: 'Version {{version}} (Build {{build}})',
    },
    reviewComposer: {
      title: 'Write Review',
      cancel: 'Cancel',
      post: 'Post',
      save: 'Save',
      ratingLabel: 'Your Rating',
      placeholder: 'Share your experience with your followers... What made this place special?',
      photosLabel: 'Photos',
      photosCount: '{count}/10',
      visibilityLabel: 'Visibility',
      visibilityFollowers: 'Followers',
      visibilitySubscribers: 'Subscribers Only',
      visibilityHelper:
        'By selecting Subscribers Only, only your paid subscribers can view full details.',
      defaultTitle: 'Great spot',
      defaultNotes: 'Sharing a quick recommendation.',
      locationFallback: 'Select a place',
      locationSearchPlaceholder: 'Search businesses, restaurants, or places...',
      locationSuggestionsTitle: 'Suggestions',
      locationSuggestionsEmpty: 'No matching places found.',
      locationResolveError: 'Could not resolve this place on the map. Please pick another suggestion.',
      photosPermissionDenied: 'Allow photo access in Settings to add photos.',
      photosPickerError: 'Could not open photo library. Please try again.',
      submitError: 'Could not save your review right now. Please try again.',
      submitTimeoutError:
        'Upload is taking longer than expected. Check your connection and try again.',
      progressCompressing: 'Preparing photo {current}/{total}',
      progressUploading: 'Uploading photo {current}/{total}',
      progressSaving: 'Finalizing your review...',
      reviewLoadError: 'Could not open this review for editing.',
    },
    reviewDetail: {
      title: 'Review',
      byLine: 'Review by {name}',
      noPhoto: 'No photo',
      premiumBadge: 'Premium Review',
      yourReview: 'Your review',
      visibilityFollowers: 'Followers',
      visibilitySubscribers: 'Subscribers',
      locationLabel: 'Location',
      mapAction: 'Map',
      mapOpenErrorTitle: 'Could not open Google Maps',
      mapOpenErrorMessage: 'Please try again.',
      experienceLabel: 'The Experience',
      socialProofTitle: 'Also reviewed by people you follow',
      socialProofFallback: 'People in your network have visited this place.',
      like: 'Like',
      saveToFavorites: 'Save to favorites',
      savedToFavorites: 'Saved',
      commentsTitle: 'Comments',
      commentsEmpty: 'No comments yet. Start the conversation.',
      commentsPlaceholder: 'Write a comment...',
      commentsSubmit: 'Post',
      commentsSubmitting: 'Posting...',
      commentDeleteTitle: 'Delete comment',
      commentDeleteMessage: 'This comment will be permanently removed.',
      commentDeleteErrorTitle: 'Could not delete comment',
      commentDeleteErrorMessage: 'Please try again.',
      likeErrorTitle: 'Could not update like',
      likeErrorMessage: 'Please try again in a moment.',
      edit: 'Edit',
      delete: 'Delete',
      deleting: 'Deleting...',
      postedOn: 'Posted on {date}',
      placeNotFound: 'This review is no longer available.',
      backToMap: 'Back to map',
      deleteTitle: 'Delete review',
      deleteMessage: 'This action cannot be undone.',
      deleteError: 'Could not delete review right now.',
      favoriteErrorTitle: 'Could not update favorite',
      favoriteErrorMessage: 'Please try again in a moment.',
      shareErrorTitle: 'Could not open share',
      shareErrorMessage: 'Please try again.',
      cancel: 'Cancel',
    },
    notifications: {
      title: 'Notifications',
      clear: 'Clear',
      clearConfirmTitle: 'Clear all notifications?',
      clearConfirmMessage: 'This will permanently remove your activity updates.',
      clearConfirmCancel: 'Cancel',
      clearConfirmConfirm: 'Clear all',
      clearErrorTitle: 'Could not clear notifications',
      clearErrorMessage: 'Please try again.',
      actionErrorTitle: 'Could not complete this action',
      actionErrorMessage: 'Please try again.',
      sectionNew: 'New Requests',
      sectionEarlier: 'Earlier Today',
      sectionWeek: 'This Week',
      emptyTitle: 'No activity yet',
      emptySubtitle: 'When people interact with you, updates will appear here.',
      accept: 'Accept',
      decline: 'Decline',
      followBack: 'Follow back',
      accepted: 'Accepted',
      declined: 'Declined',
      followRequestMessage: 'wants to follow your recommendations.',
      followStartedMessage: 'started following you.',
      followRequestAcceptedMessage: 'accepted your follow request.',
      reviewPublishedMessage: 'posted a new review:',
      reviewPublishedPremiumMessage: 'shared a Premium Review.',
      premiumTitle: 'Unlock Premium Review',
      premiumSubtitle: 'Included in your subscription',
      premiumCta: 'View',
    },
  },
  'pt-BR': {
    auth: {
      appName: 'MapFriends',
      loginTitle: 'MapFriends',
      loginSubtitle: 'Faça login para ver recomendações do seu círculo.',
      signupTitle: 'Crie seu perfil',
      signupSubtitle: 'Comece a compartilhar favoritos locais.',
      nameLabel: 'Nome',
      namePlaceholder: 'Seu nome',
      emailLabel: 'E-mail',
      emailPlaceholder: 'nome@exemplo.com',
      passwordLabel: 'Senha',
      passwordPlaceholder: 'Digite sua senha',
      confirmPasswordLabel: 'Confirmar senha',
      confirmPasswordPlaceholder: 'Digite a senha novamente',
      confirmPasswordMismatch: 'As senhas nao correspondem.',
      togglePasswordVisibility: 'Mostrar ou ocultar senha',
      forgotPassword: 'Esqueceu a senha?',
      loginButton: 'Entrar',
      signupButton: 'Criar conta',
      divider: 'Ou continue com',
      socialGoogle: 'Google',
      socialApple: 'Apple',
      noAccount: 'Não tem uma conta?',
      createAccount: 'Criar conta',
      haveAccount: 'Já tem uma conta?',
      backToLogin: 'Voltar para entrar',
      resetPasswordSent: 'E-mail de redefinição de senha enviado.',
      firebaseNotConfigured: 'A configuração do Firebase está ausente. Verifique as variáveis de ambiente.',
      authErrorInvalidCredentials: 'E-mail ou senha inválidos.',
      authErrorEmailInUse: 'Este e-mail já está em uso.',
      authErrorInvalidEmail: 'Digite um e-mail válido.',
      authErrorWeakPassword: 'A senha deve ter pelo menos 6 caracteres.',
      authErrorUserDisabled: 'Esta conta foi desativada.',
      authErrorTooManyRequests: 'Muitas tentativas. Tente novamente em alguns minutos.',
      authErrorNetwork: 'Erro de rede. Verifique sua conexão com a internet.',
      authErrorRecentLogin: 'Faça login novamente antes de excluir sua conta.',
      authErrorDeleteEmailMismatch: 'O e-mail de confirmação não corresponde ao e-mail da sua conta.',
      authErrorProviderCanceled: 'A autenticação foi cancelada.',
      authErrorProviderUnavailable: 'Este provedor de login ainda não está configurado.',
      authErrorGeneric: 'Não foi possível autenticar agora. Tente novamente.',
      loadingA11y: 'Carregando',
    },
    terms: {
      title: 'Acordos legais',
      subtitle: 'Revise nossos termos para continuar usando o mapa social.',
      section1Title: '1. Termos de Serviço',
      section1Paragraph1:
        'Ao usar nossa plataforma de recomendações com mapa social, você concorda em compartilhar seus dados de localização e preferências de visibilidade com os seguidores que você aprovou. Nosso modelo de assinatura para avaliações premium oferece acesso a conteúdo curado de especialistas locais verificados.',
      section1Paragraph2:
        'Você é responsável por manter a confidencialidade da sua conta e por todas as atividades realizadas nela. Você concorda em nos notificar imediatamente sobre qualquer uso não autorizado.',
      section2Title: '2. Resumo da Política de Privacidade',
      section2Paragraph1:
        'Sua privacidade é nossa prioridade. Só mostramos seus pins e avaliações para pessoas que você segue de volta. Seu histórico de localização é criptografado e nunca é vendido a anunciantes terceiros.',
      section2Paragraph2:
        'Avaliações premium estão sujeitas a acordos específicos de licenciamento. Copiar ou redistribuir conteúdo premium sem uma assinatura válida é estritamente proibido.',
      section3Title: '3. Padrões da Comunidade',
      section3Paragraph1:
        'Os usuários devem se abster de publicar conteúdo ofensivo, spam ou avaliações enganosas. A violação dos padrões da comunidade pode resultar em suspensão temporária ou permanente da sua conta e assinatura.',
      acceptTermsPrefix: 'Concordo com os ',
      acceptTermsLink: 'Termos de Serviço',
      acceptPrivacyPrefix: 'Concordo com a ',
      acceptPrivacyLink: 'Política de Privacidade',
      acceptButton: 'Aceitar e continuar',
      declineButton: 'Recusar e sair',
    },
    profileSetup: {
      title: 'Configuração do perfil',
      subtitle: 'Monte seu perfil para que amigos reconheçam sua atividade no mapa.',
      avatarLabel: 'Enviar avatar',
      displayNameLabel: 'Nome de exibição',
      displayNamePlaceholder: 'ex.: Alex Explorer',
      handleLabel: 'Usuário',
      handlePlaceholder: 'usuario',
      handleHelper: 'Seu identificador único no mapa.',
      handleError: 'Use 3–20 caracteres: letras minúsculas, números ou _.',
      handleChecking: 'Verificando disponibilidade do usuário...',
      handleAvailable: 'Usuário disponível.',
      handleTaken: 'Este usuário já está em uso.',
      handleReserved: 'Este usuário é reservado e não pode ser usado.',
      handleImmutable: 'Seu usuário já foi definido e não pode ser alterado.',
      handleSanitizedHelper: 'Caracteres não suportados foram removidos.',
      bioLabel: 'Bio',
      bioPlaceholder: 'Compartilhe seus lugares favoritos ou estilo de viagem...',
      bioMax: 150,
      visibilityLabel: 'Visibilidade do perfil',
      visibilityOpenTitle: 'Aberto',
      visibilityOpenDesc: 'Qualquer pessoa pode ver seu mapa',
      visibilityLockedTitle: 'Bloqueado',
      visibilityLockedDesc: 'Apenas seguidores veem pins',
      continueButton: 'Continuar',
      avatarAddA11yLabel: 'Adicionar avatar do perfil',
      avatarChangeA11yLabel: 'Alterar avatar do perfil',
      avatarA11yHint: 'Abre sua biblioteca de fotos',
      avatarPermissionDenied: 'Permita acesso às fotos nos Ajustes para escolher um avatar.',
      avatarPickerError: 'Não foi possível abrir a biblioteca de fotos. Tente novamente.',
      visibilityOpenA11yLabel: 'Definir visibilidade do perfil como aberto',
      visibilityLockedA11yLabel: 'Definir visibilidade do perfil como bloqueado',
      continueA11yLabel: 'Continuar configuração de perfil',
      continueA11yHint: 'Salva o perfil e continua para a introdução',
    },
    home: {
      tabFeed: 'Feed',
      tabMap: 'Mapa',
      filterPeopleAll: 'Pessoas: Todas',
      filterContentPremium: 'Conteúdo: Premium',
      youLabel: 'Você',
      sampleQuote: 'Elena diz: "Melhor caldo da cidade!"',
      feedSubtitle: 'Recomendações recentes do seu círculo.',
      feedTitle: 'SocialMap',
      feedMore: 'mais',
      feedPremiumLabel: 'Premium',
      feedPremiumTitle: 'Desbloqueie a avaliação completa',
      feedPremiumDesc: 'Assine o Premium para ver a nota do Mike e ler todos os detalhes.',
      feedPremiumCta: 'Assinar',
      feedEmptyTitle: 'Uma página em silêncio, à espera do seu primeiro lugar.',
      feedEmptySubtitle:
        'Ainda não há nada compartilhado. Sua próxima recomendação pode virar a memória favorita de alguém.',
      feedEmptyCta: 'Compartilhar minha primeira avaliação',
      feedEmptyFootnote: 'Deixe uma pequena marca. A cidade responde.',
      feedActionAuthTitle: 'Autenticação necessária',
      feedActionAuthMessage: 'Faça login novamente para usar esta ação.',
      feedShareTitle: 'Compartilhar avaliação',
      feedShareSubtitlePrefix: 'Compartilhar',
      feedShareSystem: 'Compartilhar pelo sistema',
      feedShareCopyLink: 'Copiar link',
      feedShareCopySuccessTitle: 'Link copiado',
      feedShareCopySuccessMessage: 'Link da avaliação copiado para a área de transferência.',
      feedShareCopyErrorTitle: 'Não foi possível copiar o link',
      feedShareCopyErrorMessage: 'Tente novamente.',
      feedShareCancel: 'Cancelar',
      feedLikeErrorTitle: 'Não foi possível atualizar curtida',
      feedLikeErrorMessage: 'Tente novamente em alguns instantes.',
      feedFavoriteErrorTitle: 'Não foi possível atualizar o favorito',
      feedFavoriteErrorMessage: 'Tente novamente em alguns instantes.',
      feedShareErrorTitle: 'Não foi possível abrir o compartilhamento',
      feedShareErrorMessage: 'Tente novamente.',
      navHome: 'Início',
      navExplore: 'Explorar',
      navActivity: 'Atividade',
      navProfile: 'Perfil',
      mapTokenMissing: 'Adicione EXPO_PUBLIC_MAPBOX_TOKEN para ativar o mapa.',
      locationPromptTitle: 'Ative sua localizacao',
      locationPromptMessage:
        'Usamos sua localizacao para mostrar recomendacoes proximas e conteudo personalizado no mapa.',
      locationPromptAllow: 'Permitir localizacao',
      locationPromptNotNow: 'Agora nao',
      exploreTitle: 'Explorar',
      exploreSubtitle: 'Pesquise e descubra novos lugares.',
    },
    search: {
      placeholder: 'Buscar por nome ou @usuario...',
      cancel: 'Cancelar',
      recentTitle: 'Pesquisas recentes',
      recentEmptyTitle: 'Nenhuma pesquisa recente',
      recentEmptySubtitle: 'Pesquise alguém e toque no perfil para salvar aqui.',
      trendingTitle: 'Criadores em alta',
      trendingEmptyTitle: 'Nenhum criador em alta agora',
      trendingEmptySubtitle: 'Conforme novas avaliações forem publicadas, os destaques da semana aparecem aqui.',
      resultsTitle: 'Pessoas',
      resultsEmptyTitle: 'Nenhuma pessoa encontrada',
      resultsEmptySubtitle: 'Tente outro nome ou usuário.',
      minQueryTitle: 'Continue digitando',
      minQuerySubtitle: 'Digite pelo menos 2 caracteres para buscar.',
      clearAll: 'Limpar tudo',
      infoMessage:
        'Para manter uma experiência curada, você só verá avaliações e pins de pessoas que segue. Conecte-se com amigos ou siga criadores em alta para preencher seu mapa.',
      follow: 'Seguir',
      following: 'Seguindo',
      request: 'Solicitar',
      requested: 'Solicitado',
      locked: 'Fechado',
      postsThisWeek: '{count} posts nesta semana',
      followErrorTitle: 'Não foi possível concluir a ação',
      followErrorMessage: 'Tente novamente.',
      proBadge: 'PRO',
    },
    profile: {
      title: 'Configurações',
      handlePrefix: '@',
      subtitle: 'Criador premium e guia',
      tabSettings: 'Configurações',
      tabFavorites: 'Favoritos',
      editProfile: 'Editar perfil',
      editScreenTitle: 'Editar perfil',
      editNameLabel: 'Nome de exibição',
      editNamePlaceholder: 'ex.: Alex Explorer',
      editHandleLabel: 'Usuário',
      editBioLabel: 'Bio',
      editBioPlaceholder: 'Compartilhe seus lugares favoritos ou estilo de viagem...',
      editAvatarLabel: 'Alterar avatar',
      editAvatarPermissionDenied: 'Permita acesso às fotos nos Ajustes para escolher um avatar.',
      editAvatarPickerError: 'Não foi possível abrir a biblioteca de fotos. Tente novamente.',
      editSave: 'Salvar alterações',
      editSaving: 'Salvando...',
      deleteAccount: 'Excluir conta',
      deleteSheetTitle: 'Excluir conta permanentemente?',
      deleteSheetMessage:
        'Esta ação não pode ser desfeita. Todos os dados do seu perfil e o acesso à conta serão removidos.',
      deleteSheetEmailLabel: 'Digite seu e-mail para confirmar',
      deleteSheetEmailPlaceholder: 'nome@exemplo.com',
      deleteSheetCancel: 'Cancelar',
      deleteSheetConfirm: 'Excluir minha conta',
      sectionPrivacy: 'Privacidade da conta',
      visibilityTitle: 'Visibilidade do perfil',
      visibilitySubtitle: 'Contas bloqueadas exigem aprovação',
      sectionCreator: 'Central do criador',
      creatorSettings: 'Configurações do criador',
      subscriberManagement: 'Gestão de assinantes',
      subscriberCount: '124',
      sectionPreferences: 'Preferências',
      manageSubscriptions: 'Gerenciar minhas assinaturas',
      manageSubscriptionsComingSoon: 'Em breve',
      manageSubscriptionsComingSoonSubtitle: 'Detalhes de assinatura e controles de cobrança aparecerão aqui quando esse recurso for lançado.',
      blockedUsers: 'Usuários bloqueados',
      blockedUsersTitle: 'Gerencie usuários bloqueados',
      blockedUsersSubtitle: 'Pessoas bloqueadas não podem interagir com seu perfil ou conteúdo até serem desbloqueadas.',
      blockedUsersEmptyTitle: 'Nenhum usuário bloqueado',
      blockedUsersEmptySubtitle: 'Quando você bloquear alguém, a pessoa aparecerá aqui para você gerenciar o acesso.',
      blockedUsersErrorTitle: 'Não foi possível carregar usuários bloqueados',
      blockedUsersErrorSubtitle: 'Puxe para baixo para tentar novamente.',
      blockedUsersUnblockLabel: 'Desbloquear',
      blockedUsersBlockedOnPrefix: 'Bloqueado em',
      blockedUsersBlockedRecently: 'recentemente',
      blockedUsersUnblockConfirmTitle: 'Desbloquear este usuário?',
      blockedUsersUnblockConfirmMessage: '{handle} poderá ver e interagir com seu conteúdo novamente.',
      blockedUsersUnblockConfirmCancel: 'Cancelar',
      blockedUsersUnblockConfirmAction: 'Desbloquear',
      blockedUsersUnblockErrorTitle: 'Não foi possível desbloquear o usuário',
      blockedUsersUnblockErrorMessage: 'Tente novamente.',
      favoritesTitle: 'Favoritos salvos',
      favoritesSubtitle: 'Lugares e avaliações que você decidiu guardar.',
      favoritesEmptyTitle: 'Nenhum favorito ainda',
      favoritesEmptySubtitle: 'Abra uma avaliação e toque em Salvar nos favoritos para montar sua lista.',
      favoritesRemoveLabel: 'Remover dos favoritos',
      logout: 'Sair',
      logoutConfirmTitle: 'Sair da sua conta?',
      logoutConfirmMessage: 'Você precisará entrar novamente para continuar.',
      logoutConfirmCancel: 'Cancelar',
      logoutConfirmConfirm: 'Sair',
      logoutErrorTitle: 'Não foi possível sair',
      logoutErrorMessage: 'Tente novamente.',
      loggingOut: 'Saindo...',
      versionLabel: 'Versão {{version}} (Build {{build}})',
    },
    reviewComposer: {
      title: 'Escrever avaliação',
      cancel: 'Cancelar',
      post: 'Publicar',
      save: 'Salvar',
      ratingLabel: 'Sua nota',
      placeholder: 'Compartilhe sua experiência... O que tornou esse lugar especial?',
      photosLabel: 'Fotos',
      photosCount: '{count}/10',
      visibilityLabel: 'Visibilidade',
      visibilityFollowers: 'Seguidores',
      visibilitySubscribers: 'Apenas assinantes',
      visibilityHelper:
        'Ao selecionar Apenas assinantes, só seus assinantes pagos podem ver todos os detalhes.',
      defaultTitle: 'Ótimo lugar',
      defaultNotes: 'Compartilhando uma recomendação rápida.',
      locationFallback: 'Selecione um lugar',
      locationSearchPlaceholder: 'Busque negócios, restaurantes ou lugares...',
      locationSuggestionsTitle: 'Sugestões',
      locationSuggestionsEmpty: 'Nenhum lugar correspondente encontrado.',
      locationResolveError: 'Não foi possível localizar esse lugar no mapa. Escolha outra sugestão.',
      photosPermissionDenied: 'Permita acesso às fotos nos Ajustes para adicionar fotos.',
      photosPickerError: 'Não foi possível abrir a biblioteca de fotos. Tente novamente.',
      submitError: 'Não foi possível salvar sua avaliação agora. Tente novamente.',
      submitTimeoutError:
        'O envio está demorando mais do que o esperado. Verifique sua conexão e tente novamente.',
      progressCompressing: 'Preparando foto {current}/{total}',
      progressUploading: 'Enviando foto {current}/{total}',
      progressSaving: 'Finalizando sua avaliação...',
      reviewLoadError: 'Não foi possível abrir esta avaliação para edição.',
    },
    reviewDetail: {
      title: 'Avaliação',
      byLine: 'Avaliação de {name}',
      noPhoto: 'Sem foto',
      premiumBadge: 'Avaliação premium',
      yourReview: 'Sua avaliação',
      visibilityFollowers: 'Seguidores',
      visibilitySubscribers: 'Assinantes',
      locationLabel: 'Localização',
      mapAction: 'Mapa',
      mapOpenErrorTitle: 'Não foi possível abrir o Google Maps',
      mapOpenErrorMessage: 'Tente novamente.',
      experienceLabel: 'A experiência',
      socialProofTitle: 'Também avaliado por pessoas que você segue',
      socialProofFallback: 'Pessoas da sua rede já visitaram este lugar.',
      like: 'Curtir',
      saveToFavorites: 'Salvar nos favoritos',
      savedToFavorites: 'Salvo',
      commentsTitle: 'Comentários',
      commentsEmpty: 'Ainda não há comentários. Seja o primeiro.',
      commentsPlaceholder: 'Escreva um comentário...',
      commentsSubmit: 'Publicar',
      commentsSubmitting: 'Publicando...',
      commentDeleteTitle: 'Excluir comentário',
      commentDeleteMessage: 'Este comentário será removido permanentemente.',
      commentDeleteErrorTitle: 'Não foi possível excluir o comentário',
      commentDeleteErrorMessage: 'Tente novamente.',
      likeErrorTitle: 'Não foi possível atualizar curtida',
      likeErrorMessage: 'Tente novamente em alguns instantes.',
      edit: 'Editar',
      delete: 'Excluir',
      deleting: 'Excluindo...',
      postedOn: 'Publicado em {date}',
      placeNotFound: 'Esta avaliação não está mais disponível.',
      backToMap: 'Voltar ao mapa',
      deleteTitle: 'Excluir avaliação',
      deleteMessage: 'Esta ação não pode ser desfeita.',
      deleteError: 'Não foi possível excluir a avaliação agora.',
      favoriteErrorTitle: 'Não foi possível atualizar o favorito',
      favoriteErrorMessage: 'Tente novamente em alguns instantes.',
      shareErrorTitle: 'Não foi possível abrir o compartilhamento',
      shareErrorMessage: 'Tente novamente.',
      cancel: 'Cancelar',
    },
    notifications: {
      title: 'Notificações',
      clear: 'Limpar',
      clearConfirmTitle: 'Limpar todas as notificações?',
      clearConfirmMessage: 'Isso removerá permanentemente suas atualizações de atividade.',
      clearConfirmCancel: 'Cancelar',
      clearConfirmConfirm: 'Limpar tudo',
      clearErrorTitle: 'Não foi possível limpar notificações',
      clearErrorMessage: 'Tente novamente.',
      actionErrorTitle: 'Não foi possível concluir esta ação',
      actionErrorMessage: 'Tente novamente.',
      sectionNew: 'Novos pedidos',
      sectionEarlier: 'Hoje mais cedo',
      sectionWeek: 'Esta semana',
      emptyTitle: 'Sem atividade ainda',
      emptySubtitle: 'Quando alguém interagir com você, as atualizações aparecerão aqui.',
      accept: 'Aceitar',
      decline: 'Recusar',
      followBack: 'Seguir de volta',
      accepted: 'Aceito',
      declined: 'Recusado',
      followRequestMessage: 'quer seguir suas recomendações.',
      followStartedMessage: 'começou a seguir você.',
      followRequestAcceptedMessage: 'aceitou seu pedido para seguir.',
      reviewPublishedMessage: 'publicou uma nova avaliação:',
      reviewPublishedPremiumMessage: 'compartilhou uma avaliação Premium.',
      premiumTitle: 'Desbloquear avaliação premium',
      premiumSubtitle: 'Incluído na sua assinatura',
      premiumCta: 'Ver',
    },
  },
} as const;

type SupportedLocale = keyof typeof STRINGS;

function resolveLocale(): SupportedLocale {
  const locale = Localization.getLocales?.()?.[0];
  const tag = (locale?.languageTag || 'en-US').toLowerCase();

  if (tag.startsWith('pt')) {
    return 'pt-BR';
  }

  return 'en-US';
}

export function getStrings() {
  return STRINGS[resolveLocale()];
}
